In [1]:
from hood_option_pricer import estimate
import pandas as pd

# HOOD strike 60 for September

Check: https://finance.yahoo.com/quote/HOOD/options/?straddle=true&date=1758240000

In [2]:
df = estimate(ticker="HOOD", 
              strike=60.0, 
              expiry="2025-09-19")

display(df)

  ticker         method  type      price  strike               expiry
0   HOOD  Black–Scholes  call  40.512538    60.0  2025-09-19T00:00:00
1   HOOD  Black–Scholes   put   0.227476    60.0  2025-09-19T00:00:00
2   HOOD   Binomial CRR  call  40.511592    60.0  2025-09-19T00:00:00
3   HOOD   Binomial CRR   put   0.226530    60.0  2025-09-19T00:00:00
4   HOOD    Monte Carlo  call  40.521006    60.0  2025-09-19T00:00:00
5   HOOD    Monte Carlo   put   0.231366    60.0  2025-09-19T00:00:00

# HOOD strike 100 for December

Check: https://finance.yahoo.com/quote/HOOD/options/?straddle=true&date=1766102400

In [3]:
df = estimate(ticker="HOOD", 
              strike=100, 
              expiry="2025-12-19")

display(df)

  ticker         method  type      price  strike               expiry
0   HOOD  Black–Scholes  call  19.090971     100  2025-12-19T00:00:00
1   HOOD  Black–Scholes   put  17.318315     100  2025-12-19T00:00:00
2   HOOD   Binomial CRR  call  19.070908     100  2025-12-19T00:00:00
3   HOOD   Binomial CRR   put  17.298252     100  2025-12-19T00:00:00
4   HOOD    Monte Carlo  call  18.969263     100  2025-12-19T00:00:00
5   HOOD    Monte Carlo   put  17.297503     100  2025-12-19T00:00:00

# COIN strike 280 for December

Check: https://finance.yahoo.com/quote/COIN/options/?straddle=true&date=1766102400

In [4]:
df = estimate(ticker="COIN", 
              strike=280, 
              expiry="2025-12-19")

display(df)

  ticker         method  type      price  strike               expiry
0   COIN  Black–Scholes  call  83.117950     280  2025-12-19T00:00:00
1   COIN  Black–Scholes   put  43.184514     280  2025-12-19T00:00:00
2   COIN   Binomial CRR  call  83.185030     280  2025-12-19T00:00:00
3   COIN   Binomial CRR   put  43.251594     280  2025-12-19T00:00:00
4   COIN    Monte Carlo  call  82.928799     280  2025-12-19T00:00:00
5   COIN    Monte Carlo   put  43.041850     280  2025-12-19T00:00:00